### ISSUE TITLE
Cannot Write, unknown type

### ISSUE THREAD

**Issue by Eerey** [felangel/hydrated_bloc#60] opened 2020-06-24 20:59 UTC
**Describe the bug**

![image](https://user-images.githubusercontent.com/7249645/85626705-bd30bd80-b66d-11ea-9ca1-99291b81358f.png)
```dart
@immutable
@CopyWith()
@HiveType(typeId: 1)
@JsonSerializable(nullable: false)
class User extends Equatable {
  /// Display name of this.
  @JsonKey(name: "displayName")
  @HiveField(0)
  final String name;

  /// Score of this.
  @HiveField(1)
  final int score;

  /// Level of this.
  @HiveField(2)
  final int level;
  // more code...
  /// Creates a [User] from Json.
  factory User.fromJson(Map<String, dynamic> json) => _$UserFromJson(json);

  /// Creates a Json from [User].
  Map<String, dynamic> toJson() => _$UserToJson(this);

```

**To Reproduce**
i think it's too much code, it worked prior on 3.1.0 perfectly, but now with hive i don't know what else to change.

**Expected behavior**
persisting data like in 3.1.0

**Screenshots**
![image](https://user-images.githubusercontent.com/7249645/85626705-bd30bd80-b66d-11ea-9ca1-99291b81358f.png)

**Logs **
```powershell
I/flutter (10060): [2020-06-24 20:54:45.136155 | ConsoleHandler | INFO]
I/flutter (10060): [2020-06-24 20:54:45.136688 | ConsoleHandler | INFO] ------- STACK TRACE -------
I/flutter (10060): [2020-06-24 20:54:45.147581 | ConsoleHandler | INFO] #0      Bloc.onError.<anonymous closure> 
package:bloc/src/bloc.dart:146
I/flutter (10060): [2020-06-24 20:54:45.147917 | ConsoleHandler | INFO] #1      Bloc.onError 
package:bloc/src/bloc.dart:147
I/flutter (10060): [2020-06-24 20:54:45.148223 | ConsoleHandler | INFO] #2      HydratedBloc.initialState 
package:hydrated_bloc/src/hydrated_bloc.dart:38
I/flutter (10060): [2020-06-24 20:54:45.148455 | ConsoleHandler | INFO] #3      CafeteriaBloc.initialState 
package:tc_frontend/…/cafeteria/cafeteria_bloc.dart:33
I/flutter (10060): [2020-06-24 20:54:45.148553 | ConsoleHandler | INFO] #4      new Bloc 
```
Paste the output of running `flutter doctor -v` here.
```powershell
[√] Flutter (Channel stable, v1.17.3, on Microsoft Windows [Version 10.0.18363.836], locale de-DE)
    • Flutter version 1.17.3 at C:\flutterSDK\flutter
    • Framework revision b041144f83 (3 weeks ago), 2020-06-04 09:26:11 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\androidsdk
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = C:\androidsdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 31.2.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[√] VS Code, 64-bit edition (version 1.45.0)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.11.0

[√] Connected device (1 available)
    • AOSP on IA Emulator • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)
```

**Additional context**
i added the hive annotations, what else do i need to do to make it work again?
Cheers and thanks for the effort :)

**Comment by orsenkucher** [comment] 2020-06-26 07:14
If  `_$UserToJson` produces valid json, hive should be fine to save it. Don't forget to call `user.toJson()` from hydrated bloc's overridden `toJson` method

When using adapter call `Hive.registerAdapter(UserAdapter());` from your `main`, where `UserAdapter` is `class UserAdapter extends TypeAdapter<User>`

**Comment by felangel** [comment] 2020-07-03 21:11
Closing this for now since there isn't enough information to reproduce the issue locally. Feel free to comment with a link to a sample which reproduces the problem and I'm happy to continue the conversation 👍

**Closed as completed by felangel** 2020-07-03 21:11 UTC
Labels: question
